version: "3.9"
services:
  gremlin-server-353:
    build: 
      context: gremlin-server
      args:
        VERSION: "3.5.3"
  
    ports:
        - "353:8182"

  gremlin-server-354:
    build: 
      context: gremlin-server
      args:
        VERSION: "3.5.4"
      
    ports:
        - "354:8182"
