version: "3"
services:
  gremlin-server-353:
    image: tinkerpop/gremlin-server:3.5.3
  
    ports:
        - "353:8182"

  gremlin-server-354:
    image: tinkerpop/gremlin-server:3.5.3

    ports:
        - "354:8182"
