version: "3.9"

services:
  gremlin-server-3.5.3:
    image: tinkerpop/gremlin-server:3.5.3
    expose: 
      - 8182

  gremlin-server-3.5.4:
    image: tinkerpop/gremlin-server:3.5.4
    expose: 
      - 8182
  
  test:
    build: .
    depends_on:
      - gremlin-server-3.5.3
      - gremlin-server-3.5.4
    
    links:
      - gremlin-server-3.5.3
      - gremlin-server-3.5.4
